### ISSUE TITLE
Windows Dallar wallet QT GUI encryption confirmation still refers to Groestlcoins

### ISSUE THREAD

**Issue by codemaster** [dallar-project/dallar#2]
Reproduction Steps:
1. Open Dallar Wallet.
2. Settings> Encrypt Wallet.
3. Dialog appears with the inconsistency.

![image](https://user-images.githubusercontent.com/75353/34636739-021062b6-f25d-11e7-9294-45f2d5934274.png)

**Comment by Allar** [comment]
Addressed in 1.2.0
